#!/bin/sh
set -e

gobump show

printf "input next version: "
read next_version

gobump set $next_version -w
ghch -w -N v$next_version

git ci -am "Checking in changes prior to tagging of version v$next_version"
git push && git push --tags

goxc -pv v$next_version
ghr v$next_version dist/v$next_version
